D 2022-12-28 00:12:13,851| DEBUG    | [factory.py:factory:<module>:19] - Not in REPL -> leaving logger event level as is.
I 2022-12-28 00:12:14,472| INFO     | [get_data.py:get_data:read_special_list_excel:137] - 成功获取登录login所有用例，共12条用例
I 2022-12-28 00:12:14,472| INFO     | [get_data.py:get_data:read_special_list_excel:138] - [['测试成功登录', '/apitest/login/', 'post', 'data', "{'username':'test01','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1000, 'Usercheck ok', '登录验证成功'], ['测试用户名为空', '/apitest/login/', 'post', 'data', "{'username':'','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1001, 'Username is null', '用户名不能为空'], ['测试密码为空', '/apitest/login/', 'post', 'data', "{'username':'test02','password':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1002, 'Password is null', '密码不能为空'], ['测试用户名和密码均为空', '/apitest/login/', 'post', 'data', "{'username':'','password':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1001, 'Username is null', '用户名不能为空'], ['测试用户名错误', '/apitest/login/', 'post', 'data', "{'username':'test03','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试密码错误', '/apitest/login/', 'post', 'data', "{'username':'test03','password':'123'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Password error', '密码错误'], ['测试用户名和密码均错误', '/apitest/login/', 'post', 'data', "{'username':'test05','password':'123'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试用户名为中文', '/apitest/login/', 'post', 'data', "{'username':'你好','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试用户名为数字', '/apitest/login/', 'post', 'data', "{'username':'123456','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试密码为无效最大边界值', '/apitest/login/', 'post', 'data', "{'username':'test05','password':'12345678945647898468464'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试用户名为特殊字符', '/apitest/login/', 'post', 'data', "{'username':'*%$','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试密码长度超过限制', '/apitest/login/', 'post', 'data', "{'username':'test15','password':'123456784948494848484486486486'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1004, 'Password error', '用户名错误']]
I 2022-12-28 00:12:14,494| INFO     | [get_data.py:get_data:read_special_rows_list_excel:160] - 成功从获取第12到12用例,共1条用例
I 2022-12-28 00:12:14,495| INFO     | [get_data.py:get_data:read_special_rows_list_excel:161] - [['测试密码长度超过限制', '/apitest/login/', 'post', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1004, 'Password error', '用户名错误']]
I 2022-12-28 00:12:14,520| INFO     | [get_data.py:get_data:read_special_rows_list_excel:160] - 成功从获取第1到4用例,共4条用例
I 2022-12-28 00:12:14,520| INFO     | [get_data.py:get_data:read_special_rows_list_excel:161] - [['验证用户名密码正确登陆成功', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "12345678",\n "userName": "root"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 0, '登录成功', 1], ['验证用户名错误登陆失败', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "12345678",\n "userName": "oot"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 501, '用户名或口令错误', 1], ['验证密码错误登陆失败', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "1234578",\n "userName": "root"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 501, '用户名或口令错误', 1], ['验证用户名密码都错误登陆失败', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "1234678",\n "userName": "rot"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 501, '用户名或口令错误', 1]]
I 2022-12-28 00:12:14,542| INFO     | [get_data.py:get_data:read_special_list_excel:137] - 成功获取注册signup所有用例，共11条用例
I 2022-12-28 00:12:14,543| INFO     | [get_data.py:get_data:read_special_list_excel:138] - [['signup_01', '测试成功注册', '/apitest/signup/', 'post', 'json', "{'username':'test06','password':'123456','confirm':'123456','name':'成功注册用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1000,'Result':'Success','Message':'注册成功'}", 'users, info', "select count(*),(select count(*) from info where name='成功注册用户') from users where username='test06' and password=md5('123456')", '(1,1)'], ['signup_02', '测试用户名为空', '/apitest/signup/', 'post', 'json', "{'username':'','password':'123456','confirm':'123456','name':'注册用户名为空用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1001,'Result':'Username is null','Message':'注册失败，用户名不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='注册用户名为空用户') from users where username='' and password=md5('123456')", '(0,0)'], ['signup_03', '测试密码为空', '/apitest/signup/', 'post', 'json', "{'username':'test07','password':'','confirm':'123456','name':'注册密码为空用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1002,'Result':'Password is null','Message':'注册失败，密码不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='注册密码为空用户') from users where username='test07' and password=md5('')", '(0,0)'], ['signup_04', '测试确认密码为空', '/apitest/signup/', 'post', 'json', "{'username':'test08','password':'123456','confirm':'','name':'注册确认密码为空用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1003,'Result':'Confirm password is null','Message':'注册失败，确认密码不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='注册确认密码为空用户') from users where username='test08' and password=md5('123456')", '(1,1)'], ['signup_05', '测试姓名为空', '/apitest/signup/', 'post', 'json', "{'username':'test09','password':'123456','confirm':'123456','name':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1004,'Result':'Name is null','Message':'注册失败，姓名不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='') from users where username='test09' and password=md5('123456')", '(0,0)'], ['signup_06', '测试参数全为空', '/apitest/signup/', 'post', 'json', "{'username':'','password':'','confirm':'','name':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1001,'Result':'Username is null','Message':'注册失败，用户名不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='') from users where username='' and password=md5('')", '(0,0)'], ['signup_07', '测试两个密码不一致', '/apitest/signup/', 'post', 'json', "{'username':'test10','password':'123456','confirm':'123','name':'注册两个密码不一致用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1009,'Result':'Confirm password error','Message':'注册失败，两个密码不一致'}", 'users, info', "select count(*),(select count(*) from info where name='注册两个密码不一致用户') from users where username='test10' and password=md5('123456')", '(0,0)'], ['signup_08', '测试用户重复注册', '/apitest/signup/', 'post', 'json', "{'username':'test11','password':'123456','confirm':'123456','name':'重复注册用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1010,'Result':'Username test11 is taken','Message':'注册失败，用户名已被占用'}", 'users, info', "select count(*),(select count(*) from info where name='重复注册用户') from users where username='test11' and password=md5('123456')", '(1,1)'], ['signup_09', '测试用户名为中文', '/apitest/signup/', 'post', 'json', '{"username":"阳靖康","password":"123456","confirm":"123456","name":"中文注册用户"}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', '{"Status":1000,"Result":"Success","Message":"注册成功"}', 'users, info', "select count(*),(select count(*) from info where name='中文注册用户') from users where username='阳靖康' and password=md5('123456')", '(1,1)'], ['signup_10', '测试用户名为特殊字符', '/apitest/signup/', 'post', 'json', '{"username":"%￥#@&*","password":"123456","confirm":"123456","name":"特殊字符用户"}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', '{"Status":1000,"Result":"Success","Message":"注册成功"}', 'users, info', "select count(*),(select count(*) from info where name='特殊字符用户') from users where username='%￥#@&*' and password=md5('123456')", '(1,1)'], ['signup_10', '测试用户名为特殊字符', '/apitest/signup/', 'post', 'json', '{"username":"test12","password":"阳靖康","confirm":"阳靖康","name":"注册密码为中文"}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', '{"Status":1000,"Result":"Success","Message":"注册成功"}', 'users, info', "select count(*),(select count(*) from info where name='注册密码为中文') from users where username='阳靖康'", '(1,1)']]
D 2022-12-28 00:12:14,548| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.address`.
D 2022-12-28 00:12:14,552| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.address` has been localized to `en_US`.
D 2022-12-28 00:12:14,555| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.automotive`.
D 2022-12-28 00:12:14,557| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.automotive` has been localized to `en_US`.
D 2022-12-28 00:12:14,580| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.bank`.
D 2022-12-28 00:12:14,583| DEBUG    | [factory.py:factory:_find_provider_class:105] - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
D 2022-12-28 00:12:14,585| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.barcode`.
D 2022-12-28 00:12:14,586| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.barcode` has been localized to `en_US`.
D 2022-12-28 00:12:14,589| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.color`.
D 2022-12-28 00:12:14,590| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.color` has been localized to `en_US`.
D 2022-12-28 00:12:14,592| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.company`.
D 2022-12-28 00:12:14,594| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.company` has been localized to `en_US`.
D 2022-12-28 00:12:14,596| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.credit_card`.
D 2022-12-28 00:12:14,596| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.credit_card` has been localized to `en_US`.
D 2022-12-28 00:12:14,598| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.currency`.
D 2022-12-28 00:12:14,599| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.currency` has been localized to `en_US`.
D 2022-12-28 00:12:14,600| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.date_time`.
D 2022-12-28 00:12:14,603| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.date_time` has been localized to `en_US`.
D 2022-12-28 00:12:14,604| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2022-12-28 00:12:14,604| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.geo`.
D 2022-12-28 00:12:14,605| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.geo` has been localized to `en_US`.
D 2022-12-28 00:12:14,606| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.internet`.
D 2022-12-28 00:12:14,609| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.internet` has been localized to `en_US`.
D 2022-12-28 00:12:14,610| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2022-12-28 00:12:14,610| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.job`.
D 2022-12-28 00:12:14,612| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.job` has been localized to `en_US`.
D 2022-12-28 00:12:14,613| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.lorem`.
D 2022-12-28 00:12:14,615| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.lorem` has been localized to `en_US`.
D 2022-12-28 00:12:14,617| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.misc`.
D 2022-12-28 00:12:14,618| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.misc` has been localized to `en_US`.
D 2022-12-28 00:12:14,619| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.person`.
D 2022-12-28 00:12:14,623| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.person` has been localized to `en_US`.
D 2022-12-28 00:12:14,628| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.phone_number`.
D 2022-12-28 00:12:14,632| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.phone_number` has been localized to `en_US`.
D 2022-12-28 00:12:14,633| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2022-12-28 00:12:14,633| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2022-12-28 00:12:14,633| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.ssn`.
D 2022-12-28 00:12:14,637| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.ssn` has been localized to `en_US`.
D 2022-12-28 00:12:14,638| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2022-12-28 00:12:14,639| DEBUG    | [conf.py:conf:conf_get_db:30] - 读数据库服务器配置文件/Users/yangjingkang/PycharmProjects/YJK_api-master/confs/db.conf成功，数据库信息是{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
I 2022-12-28 00:12:14,644| INFO     | [mysql.py:mysql:connect:28] - ===============>成功连接数据库,参数为：{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}<===================
I 2022-12-28 00:12:14,644| INFO     | [preposition_fixture.py:preposition_fixture:connect_db:29] - *********************开始数据库连接*********************
I 2022-12-28 00:12:14,645| INFO     | [preposition_fixture.py:preposition_fixture:get_usernm_passwd:44] - ==========开始获取获取用户信息==========
I 2022-12-28 00:12:14,647| INFO     | [preposition_fixture.py:preposition_fixture:get_usernm_passwd:47] - ==========成功获取用户信息：admin,e10adc3949ba59abbe56e057f20f883e ==========
D 2022-12-28 00:12:14,650| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE id=4<=====成功
D 2022-12-28 00:12:14,652| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE id=4<=====成功
D 2022-12-28 00:12:14,654| DEBUG    | [mysql.py:mysql:insert_one:44] - 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(4, 'test01', md5('123456'))<=====成功
D 2022-12-28 00:12:14,655| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE id=5<=====成功
D 2022-12-28 00:12:14,657| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE id=5<=====成功
D 2022-12-28 00:12:14,658| DEBUG    | [mysql.py:mysql:insert_one:44] - 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(5, 'test02', md5('123456'))<=====成功
D 2022-12-28 00:12:14,660| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>INSERT INTO info(id, name) VALUES(5, '登录密码为空用户')<=====成功
D 2022-12-28 00:12:14,661| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='登录用户名错误用户'<=====成功
D 2022-12-28 00:12:14,662| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test03'<=====成功
D 2022-12-28 00:12:14,663| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE id=6<=====成功
D 2022-12-28 00:12:14,665| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE id=6<=====成功
D 2022-12-28 00:12:14,667| DEBUG    | [mysql.py:mysql:insert_one:44] - 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(6, 'test04', md5('123456'))<=====成功
D 2022-12-28 00:12:14,668| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>INSERT INTO info(id, name) VALUES(6, '登录密码错误用户')<=====成功
D 2022-12-28 00:12:14,669| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='登录用户名与密码均错误用户'<=====成功
D 2022-12-28 00:12:14,670| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test05'<=====成功
D 2022-12-28 00:12:14,672| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE id=8<=====成功
D 2022-12-28 00:12:14,674| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE id=8<=====成功
D 2022-12-28 00:12:14,675| DEBUG    | [mysql.py:mysql:insert_one:44] - 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(8, 'test15', md5('123456'))<=====成功
D 2022-12-28 00:12:14,677| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>INSERT INTO info(id, name) VALUES(8, '密码超过限制长度')<=====成功
D 2022-12-28 00:12:14,686| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,689| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 70
D 2022-12-28 00:12:14,690| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test01', 'password': '123456'}}
D 2022-12-28 00:12:14,690| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1000
D 2022-12-28 00:12:14,691| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1000
I 2022-12-28 00:12:14,691| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,691| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Usercheck ok
D 2022-12-28 00:12:14,691| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Usercheck ok
I 2022-12-28 00:12:14,691| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,692| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：登录验证成功
D 2022-12-28 00:12:14,692| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：登录验证成功
I 2022-12-28 00:12:14,692| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,698| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,700| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 77
D 2022-12-28 00:12:14,701| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': '', 'password': '123456'}}
D 2022-12-28 00:12:14,702| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1001
D 2022-12-28 00:12:14,702| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1001
I 2022-12-28 00:12:14,702| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,702| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username is null
D 2022-12-28 00:12:14,702| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username is null
I 2022-12-28 00:12:14,703| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,703| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名不能为空
D 2022-12-28 00:12:14,703| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名不能为空
I 2022-12-28 00:12:14,703| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,711| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,714| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 74
D 2022-12-28 00:12:14,715| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test02', 'password': ''}}
D 2022-12-28 00:12:14,715| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1002
D 2022-12-28 00:12:14,715| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1002
I 2022-12-28 00:12:14,715| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,716| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Password is null
D 2022-12-28 00:12:14,716| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Password is null
I 2022-12-28 00:12:14,716| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,717| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：密码不能为空
D 2022-12-28 00:12:14,717| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：密码不能为空
I 2022-12-28 00:12:14,717| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,725| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,728| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 77
D 2022-12-28 00:12:14,729| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': '', 'password': ''}}
D 2022-12-28 00:12:14,729| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1001
D 2022-12-28 00:12:14,729| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1001
I 2022-12-28 00:12:14,730| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,730| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username is null
D 2022-12-28 00:12:14,730| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username is null
I 2022-12-28 00:12:14,731| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,731| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名不能为空
D 2022-12-28 00:12:14,731| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名不能为空
I 2022-12-28 00:12:14,731| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,739| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,743| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,743| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test03', 'password': '123456'}}
D 2022-12-28 00:12:14,744| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,744| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,745| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,745| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,745| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username error
I 2022-12-28 00:12:14,745| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,746| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名错误
D 2022-12-28 00:12:14,746| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
I 2022-12-28 00:12:14,746| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,754| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,757| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,758| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test03', 'password': '123'}}
D 2022-12-28 00:12:14,758| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,758| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,759| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,759| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,759| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Password error
E 2022-12-28 00:12:14,759| ERROR    | [asserts.py:asserts:assert_message:47] - 断言失败，Response_Message实际结果为：Username error，Response预期结果为：Password error
E 2022-12-28 00:12:14,760| ERROR    | [asserts.py:asserts:assert_message:48] - 断言用例不通过！
D 2022-12-28 00:12:14,866| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,870| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,871| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test05', 'password': '123'}}
D 2022-12-28 00:12:14,871| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,872| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,872| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,872| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,873| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username error
I 2022-12-28 00:12:14,873| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,873| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名错误
D 2022-12-28 00:12:14,873| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
I 2022-12-28 00:12:14,874| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,879| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,882| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,883| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': '你好', 'password': '123456'}}
D 2022-12-28 00:12:14,883| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,883| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,884| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,884| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,884| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username error
I 2022-12-28 00:12:14,884| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,884| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名错误
D 2022-12-28 00:12:14,885| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
I 2022-12-28 00:12:14,885| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,891| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,894| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,894| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': '123456', 'password': '123456'}}
D 2022-12-28 00:12:14,895| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,895| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,895| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,895| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,895| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username error
I 2022-12-28 00:12:14,896| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,896| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名错误
D 2022-12-28 00:12:14,896| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
I 2022-12-28 00:12:14,896| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,903| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,907| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,908| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test05', 'password': '12345678945647898468464'}}
D 2022-12-28 00:12:14,909| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,909| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,909| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,910| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,910| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username error
I 2022-12-28 00:12:14,910| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,911| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名错误
D 2022-12-28 00:12:14,911| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
I 2022-12-28 00:12:14,912| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,922| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,928| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 69
D 2022-12-28 00:12:14,929| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': '*%$', 'password': '123456'}}
D 2022-12-28 00:12:14,930| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1003
D 2022-12-28 00:12:14,930| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1003
I 2022-12-28 00:12:14,930| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,931| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Username error
D 2022-12-28 00:12:14,931| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Username error
I 2022-12-28 00:12:14,931| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,932| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名错误
D 2022-12-28 00:12:14,932| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
I 2022-12-28 00:12:14,932| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,949| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:14,954| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 78
D 2022-12-28 00:12:14,955| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test15', 'password': '123456784948494848484486486486'}}
D 2022-12-28 00:12:14,955| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：1004
D 2022-12-28 00:12:14,956| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：1004
I 2022-12-28 00:12:14,956| INFO     | [asserts.py:asserts:assert_code:33] - 断言Code用例通过！
D 2022-12-28 00:12:14,957| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：Password error
D 2022-12-28 00:12:14,957| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：Password error
I 2022-12-28 00:12:14,957| INFO     | [asserts.py:asserts:assert_message:45] - 断言Message用例通过！
D 2022-12-28 00:12:14,958| DEBUG    | [asserts.py:asserts:assert_message:42] - Response_Message实际结果为：用户名或密码错误
D 2022-12-28 00:12:14,958| DEBUG    | [asserts.py:asserts:assert_message:43] - Response_Message预期结果为：用户名错误
E 2022-12-28 00:12:14,958| ERROR    | [asserts.py:asserts:assert_message:47] - 断言失败，Response_Message实际结果为：用户名或密码错误，Response预期结果为：用户名错误
E 2022-12-28 00:12:14,958| ERROR    | [asserts.py:asserts:assert_message:48] - 断言用例不通过！
I 2022-12-28 00:12:14,972| INFO     | [preposition_fixture.py:preposition_fixture:connect_db:31] - *********************开始关闭数据库连接*********************
D 2022-12-28 00:12:14,972| DEBUG    | [mysql.py:mysql:close_db:165] - ==============================关闭数据库成功===============================
D 2022-12-28 00:12:14,994| DEBUG    | [conf.py:conf:conf_get_db:30] - 读数据库服务器配置文件/Users/yangjingkang/PycharmProjects/YJK_api-master/confs/db.conf成功，数据库信息是{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
I 2022-12-28 00:12:14,999| INFO     | [mysql.py:mysql:connect:28] - ===============>成功连接数据库,参数为：{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}<===================
I 2022-12-28 00:12:14,999| INFO     | [preposition_fixture.py:preposition_fixture:connect_db:30] - *********************开始数据库连接*********************
D 2022-12-28 00:12:15,002| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='成功注册用户'<=====成功
D 2022-12-28 00:12:15,004| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test06'<=====成功
D 2022-12-28 00:12:15,006| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='注册密码为空用户'<=====成功
D 2022-12-28 00:12:15,008| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='注册确认密码为空用户'<=====成功
D 2022-12-28 00:12:15,011| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test08'<=====成功
D 2022-12-28 00:12:15,013| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test09'<=====成功
D 2022-12-28 00:12:15,014| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='注册两个密码不一致用户'<=====成功
D 2022-12-28 00:12:15,016| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test10'<=====成功
D 2022-12-28 00:12:15,018| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE id=7<=====成功
D 2022-12-28 00:12:15,020| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE id=7<=====成功
D 2022-12-28 00:12:15,022| DEBUG    | [mysql.py:mysql:insert_one:44] - 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(7, 'test11', md5('123456'))<=====成功
D 2022-12-28 00:12:15,025| DEBUG    | [mysql.py:mysql:insert_one:44] - 执行SQL语句=====>INSERT INTO info(id, name) VALUES(7, '重复注册用户')<=====成功
D 2022-12-28 00:12:15,026| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='中文注册用户'<=====成功
D 2022-12-28 00:12:15,029| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='阳靖康'<=====成功
D 2022-12-28 00:12:15,032| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='特殊字符用户'<=====成功
D 2022-12-28 00:12:15,035| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='%￥#@&*'<=====成功
D 2022-12-28 00:12:15,037| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM info WHERE name='注册密码为中文'<=====成功
D 2022-12-28 00:12:15,039| DEBUG    | [mysql.py:mysql:delete_one:94] - 执行SQL语句=====>DELETE FROM users WHERE username='test12'<=====成功
D 2022-12-28 00:12:15,042| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,050| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 59
D 2022-12-28 00:12:15,051| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test06', 'password': '123456', 'confirm': '123456', 'name': '成功注册用户'}}
D 2022-12-28 00:12:15,052| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
D 2022-12-28 00:12:15,052| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
I 2022-12-28 00:12:15,052| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,054| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(1, 1)
D 2022-12-28 00:12:15,054| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(1, 1)
I 2022-12-28 00:12:15,054| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,063| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,067| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 92
D 2022-12-28 00:12:15,068| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': '', 'password': '123456', 'confirm': '123456', 'name': '注册用户名为空用户'}}
D 2022-12-28 00:12:15,069| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1001, 'Result': 'Username is null', 'Message': '注册失败，用户名不能为空'}
D 2022-12-28 00:12:15,069| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1001, 'Result': 'Username is null', 'Message': '注册失败，用户名不能为空'}
I 2022-12-28 00:12:15,070| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,072| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(0, 0)
D 2022-12-28 00:12:15,073| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(0, 0)
I 2022-12-28 00:12:15,073| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,080| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,083| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 89
D 2022-12-28 00:12:15,084| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test07', 'password': '', 'confirm': '123456', 'name': '注册密码为空用户'}}
D 2022-12-28 00:12:15,085| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1002, 'Result': 'Password is null', 'Message': '注册失败，密码不能为空'}
D 2022-12-28 00:12:15,085| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1002, 'Result': 'Password is null', 'Message': '注册失败，密码不能为空'}
I 2022-12-28 00:12:15,086| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,088| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(0, 0)
D 2022-12-28 00:12:15,088| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(0, 0)
I 2022-12-28 00:12:15,088| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,095| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,103| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 103
D 2022-12-28 00:12:15,104| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test08', 'password': '123456', 'confirm': '', 'name': '注册确认密码为空用户'}}
D 2022-12-28 00:12:15,105| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1003, 'Result': 'Confirm password is null', 'Message': '注册失败，确认密码不能为空'}
D 2022-12-28 00:12:15,105| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1003, 'Result': 'Confirm password is null', 'Message': '注册失败，确认密码不能为空'}
I 2022-12-28 00:12:15,105| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,106| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(1, 1)
D 2022-12-28 00:12:15,107| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(1, 1)
I 2022-12-28 00:12:15,107| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,113| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,116| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 85
D 2022-12-28 00:12:15,116| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test09', 'password': '123456', 'confirm': '123456', 'name': ''}}
D 2022-12-28 00:12:15,117| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1004, 'Result': 'Name is null', 'Message': '注册失败，姓名不能为空'}
D 2022-12-28 00:12:15,117| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1004, 'Result': 'Name is null', 'Message': '注册失败，姓名不能为空'}
I 2022-12-28 00:12:15,117| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,119| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(0, 0)
D 2022-12-28 00:12:15,119| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(0, 0)
I 2022-12-28 00:12:15,119| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,128| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,131| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 92
D 2022-12-28 00:12:15,132| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': '', 'password': '', 'confirm': '', 'name': ''}}
D 2022-12-28 00:12:15,133| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1001, 'Result': 'Username is null', 'Message': '注册失败，用户名不能为空'}
D 2022-12-28 00:12:15,133| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1001, 'Result': 'Username is null', 'Message': '注册失败，用户名不能为空'}
I 2022-12-28 00:12:15,134| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,136| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(0, 0)
D 2022-12-28 00:12:15,136| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(0, 0)
I 2022-12-28 00:12:15,136| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,145| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,147| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 98
D 2022-12-28 00:12:15,148| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test10', 'password': '123456', 'confirm': '123', 'name': '注册两个密码不一致用户'}}
D 2022-12-28 00:12:15,148| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1009, 'Result': 'Confirm password error', 'Message': '注册失败，两个密码不一致'}
D 2022-12-28 00:12:15,149| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1009, 'Result': 'Confirm password error', 'Message': '注册失败，两个密码不一致'}
I 2022-12-28 00:12:15,149| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,151| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(0, 0)
D 2022-12-28 00:12:15,151| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(0, 0)
I 2022-12-28 00:12:15,152| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,163| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,169| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 100
D 2022-12-28 00:12:15,170| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test11', 'password': '123456', 'confirm': '123456', 'name': '重复注册用户'}}
D 2022-12-28 00:12:15,171| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1010, 'Result': 'Username test11 is taken', 'Message': '注册失败，用户名已被占用'}
D 2022-12-28 00:12:15,171| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1010, 'Result': 'Username test11 is taken', 'Message': '注册失败，用户名已被占用'}
I 2022-12-28 00:12:15,172| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,175| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(1, 1)
D 2022-12-28 00:12:15,176| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(1, 1)
I 2022-12-28 00:12:15,176| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,184| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,190| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 59
D 2022-12-28 00:12:15,191| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': '阳靖康', 'password': '123456', 'confirm': '123456', 'name': '中文注册用户'}}
D 2022-12-28 00:12:15,191| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
D 2022-12-28 00:12:15,192| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
I 2022-12-28 00:12:15,192| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,194| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(1, 1)
D 2022-12-28 00:12:15,194| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(1, 1)
I 2022-12-28 00:12:15,195| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,204| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,212| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 59
D 2022-12-28 00:12:15,213| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': '%￥#@&*', 'password': '123456', 'confirm': '123456', 'name': '特殊字符用户'}}
D 2022-12-28 00:12:15,213| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
D 2022-12-28 00:12:15,214| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
I 2022-12-28 00:12:15,214| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,216| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(1, 1)
D 2022-12-28 00:12:15,217| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(1, 1)
I 2022-12-28 00:12:15,217| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
D 2022-12-28 00:12:15,228| DEBUG    | [connectionpool.py:connectionpool:_new_conn:227] - Starting new HTTP connection (1): 172.16.9.128:80
D 2022-12-28 00:12:15,237| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - http://172.16.9.128:80 "POST /apitest/signup/ HTTP/1.1" 200 59
D 2022-12-28 00:12:15,238| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/signup/', 'method': 'post', 'json': {'username': 'test12', 'password': '阳靖康', 'confirm': '阳靖康', 'name': '注册密码为中文'}}
D 2022-12-28 00:12:15,239| DEBUG    | [asserts.py:asserts:asserts:18] - Response实际结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
D 2022-12-28 00:12:15,239| DEBUG    | [asserts.py:asserts:asserts:19] - Response预期结果为：{'Status': 1000, 'Result': 'Success', 'Message': '注册成功'}
I 2022-12-28 00:12:15,239| INFO     | [asserts.py:asserts:asserts:21] - 断言用例通过！
D 2022-12-28 00:12:15,242| DEBUG    | [mysql.py:mysql:asserts_db:152] - 验库的预期结果：(1, 1)
D 2022-12-28 00:12:15,242| DEBUG    | [mysql.py:mysql:asserts_db:153] - 验库的实际结果：(1, 1)
I 2022-12-28 00:12:15,242| INFO     | [mysql.py:mysql:asserts_db:155] - 验证数据库用例通过！
I 2022-12-28 00:12:15,245| INFO     | [preposition_fixture.py:preposition_fixture:connect_db:32] - *********************开始关闭数据库连接*********************
D 2022-12-28 00:12:15,246| DEBUG    | [mysql.py:mysql:close_db:165] - ==============================关闭数据库成功===============================
