DEBUG    urllib3.connectionpool:connectionpool.py:227 Starting new HTTP connection (1): 172.16.9.128:80
DEBUG    urllib3.connectionpool:connectionpool.py:452 http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 78
DEBUG    root:requeststart.py:22 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test15', 'password': '123456784948494848484486486486'}}
DEBUG    root:asserts.py:30 Response_Code实际结果为：1004
DEBUG    root:asserts.py:31 Response_Code预期结果为：1004
INFO     root:asserts.py:33 断言Code用例通过！
DEBUG    root:asserts.py:42 Response_Message实际结果为：Password error
DEBUG    root:asserts.py:43 Response_Message预期结果为：Password error
INFO     root:asserts.py:45 断言Message用例通过！
DEBUG    root:asserts.py:42 Response_Message实际结果为：用户名或密码错误
DEBUG    root:asserts.py:43 Response_Message预期结果为：用户名错误
ERROR    root:asserts.py:47 断言失败，Response_Message实际结果为：用户名或密码错误，Response预期结果为：用户名错误
ERROR    root:asserts.py:48 断言用例不通过！
INFO     root:preposition_fixture.py:31 *********************开始关闭数据库连接*********************
DEBUG    root:mysql.py:165 ==============================关闭数据库成功===============================