DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): 192.168.61.136:80
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://192.168.61.136:80 "POST /apitest/login/ HTTP/1.1" 200 78
DEBUG    root:requests.py:22 发起请求的参数为：{'url': 'http://192.168.61.136:80/apitest/login/', 'method': 'post', 'data': {'username': 'test15', 'password': '123456784948494848484486486486'}}
DEBUG    root:asserts.py:17 Response实际结果为：{'Status': 1004, 'Result': 'Password error', 'Message': '用户名或密码错误'}
DEBUG    root:asserts.py:18 Response预期结果为：{'Status': 1004, 'Result': 'Password error', 'Message': '用户名或密码错误'}
INFO     root:asserts.py:20 断言用例通过！
DEBUG    root:mysql.py:158 ==============================关闭数据库成功===============================